name: QA

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0']

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none

      - run: composer install --no-interaction --no-progress
      - run: vendor/bin/tester -C tests/cases
